export const assets: any = {
    logo: require('./logo/logo.png'),
    loginLogo: require('./logo/loginLogo.png'),
    faviconLogo: require('./logo/faviconLogo.png'),
    facebookLogo: require('./logo/facebookLogo.png'),
    googleLogo: require('./logo/googleLogo.png'),
    decorImg: require('./logo/decorLogin.jpg'),
    chairImg: require('./logo/chair.png'),
    signInSignUpBG: require('./images/signInSignUpBG.jpg'),
    logoImage: require('./logo/logoImage.png'),
    background: require('./images/background.png'),
    // homepage
    banner: require('./images/Banner.png'),
    image1: require('./images/homepage/Image1.png'),
    image2: require('./images/homepage/Image2.png'),
    image3: require('./images/homepage/Image3.png'),
    image4: require('./images/homepage/Image4.png'),
    image5: require('./images/homepage/Image5.png'),
    image6: require('./images/homepage/Image6.png'),
    image7: require('./images/homepage/Image7.png'),
    image8: require('./images/homepage/Image8.png'),
    image9: require('./images/homepage/Image9.png'),
    image10: require('./images/homepage/Image10.png'),
    image11: require('./images/homepage/Image11.png'),
    image12: require('./images/homepage/Image12.png'),
    image13: require('./images/homepage/Image13.png'),
    image14: require('./images/homepage/Image14.png'),
    image15: require('./images/homepage/Image15.png'),
    image16: require('./images/homepage/Image16.png'),
    bedroom: require('./images/homepage/Bedroom.png'),
    dining: require('./images/homepage/Dining.png'),
    living: require('./images/homepage/Living.png'),
    syltherine: require('./images/homepage/Syltherine.png'),
    // product-details-page
    asgaardSofa1: require('./images/product-details-page/AsgaardSofa1.png'),
    asgaardSofa2: require('./images/product-details-page/AsgaardSofa2.png'),
    asgaardSofa3: require('./images/product-details-page/AsgaardSofa3.png'),
    asgaardSofa4: require('./images/product-details-page/AsgaardSofa4.png'),
    asgaardSofa5: require('./images/product-details-page/AsgaardSofa5.png'),
    // description
    asgaardSofa6: require('./images/description/AsgaardSofa6.png'),
    asgaardSofa7: require('./images/description/AsgaardSofa7.png'),
    // about
    company: require('./images/aboutpage/company.png'),
    commitment: require('./images/aboutpage/commitment.jpg'),
    // GiaBao: require('./images/aboutpage/GiaBao.png'),
    // CongBang: require('./images/aboutpage/CongBang.png'),
    // MinhVu: require('./images/aboutpage/MinhVu.png'),
    // MinhHuy: require('./images/aboutpage/MinhHuy.jpg'),
    // profile
    avatar: require('./images/avatar.jpg'),
    // footer
    freeShipping: require('./images/footer/FreeShipping.png'),
    highQuality: require('./images/footer/HighQuality.png'),
    support: require('./images/footer/Support.png'),
    warrantyProtection: require('./images/footer/WarrantyProtection.png'),
};
